name: barberpos_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.3+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.10
  google_sign_in: ^6.2.1
  pretty_dio_logger: ^1.3.1
  qr_flutter: ^4.1.0
  isar_community: 
  isar_community_flutter_libs: 
  path_provider: ^2.1.4
  collection: ^1.18.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  change_app_package_name: ^1.5.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  isar_community_generator: 
  build_runner: ^2.4.9
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
